# home computer 配置

spring:
  application:
    name: ubsp-be-home
    
  # 数据库配置 (家庭电脑的虚拟机地址)
  datasource:
    url: jdbc:mysql://192.168.1.4:3306/ubsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: rootTsk@123
    
  # Redis配置  
  data:
    redis:
      host: 192.168.1.4
      port: 6379
      database: 0
      password: # 如果有密码则填写

# SeaTunnel 配置
seatunnel:
  api:
    base-url: http://192.168.1.4:8082
    # 认证方式: none, basic, bearer, token, custom
    auth-type: none
    # Basic认证配置（当auth-type为basic时使用）
    # username: your-username
    # password: your-password
    # Token认证配置（当auth-type为bearer/token/custom时使用）
    # token: your-token
    # auth-header: Authorization  # 自定义认证头名称（仅当auth-type为custom时使用）

# 日志配置
logging:
  level:
    com.udan.ubsp: debug
    root: info