# 生产环境配置

spring:
  application:
    name: ubsp-be-prod
    
  # 数据库配置 (生产环境)
  datasource:
    url: jdbc:mysql://prod-mysql-server:3306/ubsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ubsp_user
    password: ${DB_PASSWORD} # 生产环境建议使用环境变量
    
  # Redis配置  
  data:
    redis:
      host: prod-redis-server
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD} # 生产环境建议使用环境变量

# SeaTunnel 配置
seatunnel:
  api:
    base-url: ${SEATUNNEL_API_BASE_URL:http://seatunnel-server:8082}
    # 认证方式: none, basic, bearer, token, custom
    auth-type: ${SEATUNNEL_AUTH_TYPE:none}
    # Basic认证配置
    username: ${SEATUNNEL_USERNAME:}
    password: ${SEATUNNEL_PASSWORD:}
    # Token认证配置
    token: ${SEATUNNEL_TOKEN:}
    auth-header: ${SEATUNNEL_AUTH_HEADER:Authorization}

# 生产环境日志配置
logging:
  level:
    com.udan.ubsp: info
    root: warn
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ubsp-be.log