# 生产环境配置

spring:
  application:
    name: bdsp-be-prod
    
  # 数据库配置 (生产环境)
  datasource:
    url: jdbc:mysql://prod-mysql-server:3306/bdsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: bdsp_user
    password: ${DB_PASSWORD} # 生产环境建议使用环境变量
    
  # Redis配置  
  data:
    redis:
      host: prod-redis-server
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD} # 生产环境建议使用环境变量

# 生产环境日志配置
logging:
  level:
    com.udan.bdsp: info
    root: warn
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bdsp-be.log